apiVersion: v1
kind: ConfigMap
metadata:
  name: "inject-config"
data:
  config.yaml: |
    enable: true
    proxy_port: 4001
    cli_tools_image: dragonflyoss/cli-tools:latest
    cli_tools_dir_path: /dragonfly-tools

